"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'vi' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Theme
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    system: "System",
    // Admin & General
    dashboard: "Dashboard",
    testLibrary: "Test Library",
    students: "Students",
    results: "Results",
    activity: "Activity Logs",
    logout: "Log out",
    adminConsole: "Admin Console",
    statusActive: "Status: Active",
    lastSync: "Last Sync",
    accessKey: "Access Key",
    weeklySchedule: "Weekly Schedule",
    totalTests: "Total Tests",
    totalStudents: "Total Students",
    testResults: "Test Results",
    avgScore: "Avg. Score",
    activityTrend: "Activity Trend",
    recentResults: "Recent Results",
    seeAllResults: "See All Results",
    quickActions: "Quick Actions",
    createTest: "Create Test",
    manageTests: "Manage Tests",
    gsCode: "GS Code",
    syncData: "Sync Data",
    seedData: "Seed Library",
    searchTests: "Search tests...",
    newTest: "New Test",
    id: "ID",
    title: "Title",
    category: "Category",
    actions: "Actions",
    questions: "QUESTIONS",
    edit: "Edit",
    delete: "Delete",
    studentList: "Student List",
    addStudent: "Add Student",
    studentInfo: "Student Info",
    role: "Role",
    testsDone: "Tests Done",
    fullResultHistory: "Full Result History",
    date: "Date",
    student: "Student",
    email: "Email",
    score: "Score",
    result: "Result",
    passRate: "Pass Rate",
    excellent: "EXCELLENT",
    pass: "PASS",
    fail: "FAIL",
    saveChanges: "Save Changes",
    addMultiple: "Add Multiple",
    studentManagement: "Student Management",
    questionList: "Question List",
    manageQuestions: "Manage the questions for this test",
    recentSubmissions: "Latest student submissions",
    weeklyKeys: "Keys change automatically at midnight.",
    noTests: "No Tests Found",
    noStudents: "No students registered",
    noResults: "No results yet",
    waitingFirst: "Waiting for the first student submission...",
    confirmDeleteTitle: "Are you sure?",
    confirmDeleteDesc: "This will permanently remove this item and all its associated data. This action cannot be undone.",
    cancel: "Cancel",
    timestamp: "Timestamp",
    event: "Event",
    systemActivity: "System Activity Logs",
    monitorAccess: "Monitor student login/logout events",
    ipAddress: "IP Address",
    device: "Device",
    sessionArchive: "Session Archive",
    identityRegistry: "Identity Registry",
    identityKey: "Identity Key",
    accessProtocol: "Access Protocol",
    terminateSession: "Terminate Session",
    registryOverview: "Registry Overview",
    quickProtocol: "Quick Protocol",
    activeModules: "Active Modules",
    structuralIntegrity: "Structural integrity: 100% Optimal",
    injectNewTest: "Inject New Test",
    viewSetupGuide: "View Setup Guide",
    noLogsDetected: "No Logs Detected",
    exploreLibrary: "Explore Library",
    historicalInteraction: "Your historical interaction with the DNTRNG Registry",
    // Landing Page
    library: "Library",
    setupGuide: "Setup Guide",
    heroBadge: "Professional Assessment Engine",
    heroTitleMain: "Testing",
    heroTitleItalic: "Re-imagined.",
    heroDesc: "The high-performance platform for interactive assessments, visual learning, and real-time intelligence tracking.",
    enterLibrary: "Enter Library",
    tryDemo: "Try Demo",
    builtForLearning: "Built for Learning",
    masterSkills: "Master skills with deep interactions.",
    feature1Title: "Visual Hotspots",
    feature1Desc: "Interact with image-based challenges using precision mapping.",
    feature2Title: "Logical Sequence",
    feature2Desc: "Drag and drop modules to organize complex sequences.",
    feature3Title: "Instant Feedback",
    feature3Desc: "Get real-time insights into your performance levels.",
    ctaTitle: "Start your",
    ctaItalic: "Assessment.",
    ctaDesc: "No setup required for students. Simply browse the library and begin your journey.",
    openLibrary: "Open Library",
    footerDesc: "Empowering students and educators with precision assessment protocols and real-time intelligence.",
    platform: "Platform",
    resources: "Resources",
    setupProtocol: "Setup Protocol",
    identityGuide: "Identity Guide",
    cloudSync: "Cloud Sync",
    systemOptimal: "System: Optimal"
  },
  vi: {
    // Theme
    lightMode: "Chế độ Sáng",
    darkMode: "Chế độ Tối",
    system: "Hệ thống",
    // Admin & General
    dashboard: "Bảng điều khiển",
    testLibrary: "Thư viện bài thi",
    students: "Học sinh",
    results: "Kết quả",
    activity: "Lịch sử hoạt động",
    logout: "Đăng xuất",
    adminConsole: "Quản trị",
    statusActive: "Trạng thái: Hoạt động",
    lastSync: "Đồng bộ cuối",
    accessKey: "Mã truy cập",
    weeklySchedule: "Lịch hàng tuần",
    totalTests: "Tổng bài thi",
    totalStudents: "Tổng học sinh",
    testResults: "Kết quả thi",
    avgScore: "Điểm trung bình",
    activityTrend: "Xu hướng hoạt động",
    recentResults: "Kết quả gần đây",
    seeAllResults: "Xem tất cả",
    quickActions: "Thao tác nhanh",
    createTest: "Tạo bài thi",
    manageTests: "Quản lý bài thi",
    gsCode: "Mã GS",
    syncData: "Đồng bộ dữ liệu",
    seedData: "Nạp dữ liệu mẫu",
    searchTests: "Tìm kiếm bài thi...",
    newTest: "Bài thi mới",
    id: "ID",
    title: "Tiêu đề",
    category: "Danh mục",
    actions: "Hành động",
    questions: "CÂU HỎI",
    edit: "Sửa",
    delete: "Xóa",
    studentList: "Danh sách học sinh",
    addStudent: "Thêm học sinh",
    studentInfo: "Thông tin học sinh",
    role: "Vai trò",
    testsDone: "Bài đã làm",
    fullResultHistory: "Lịch sử kết quả",
    date: "Ngày",
    student: "Học sinh",
    email: "Email",
    score: "Điểm số",
    result: "Kết quả",
    passRate: "Tỷ lệ đạt",
    excellent: "XUẤT SẮC",
    pass: "ĐẠT",
    fail: "KHÔNG ĐẠT",
    saveChanges: "Lưu thay đổi",
    addMultiple: "Thêm nhiều học sinh",
    studentManagement: "Quản lý học sinh",
    questionList: "Danh sách câu hỏi",
    manageQuestions: "Quản lý câu hỏi cho bài thi này",
    recentSubmissions: "Các bài nộp mới nhất",
    weeklyKeys: "Mã thay đổi tự động vào nửa đêm.",
    noTests: "Không tìm thấy bài thi nào",
    noStudents: "Chưa có học sinh đăng ký",
    noResults: "Chưa có kết quả",
    waitingFirst: "Đang chờ bài nộp đầu tiên từ học sinh...",
    confirmDeleteTitle: "Bạn có chắc chắn không?",
    confirmDeleteDesc: "Thao tác này sẽ xóa vĩnh viễn mục này và tất cả dữ liệu liên quan. Hành động này không thể hoàn tác.",
    cancel: "Hủy",
    timestamp: "Thời gian",
    event: "Sự kiện",
    systemActivity: "Nhật ký hệ thống",
    monitorAccess: "Theo dõi đăng nhập/đăng xuất của học sinh",
    ipAddress: "Địa chỉ IP",
    device: "Thiết bị",
    sessionArchive: "Kho lưu trữ phiên",
    identityRegistry: "Đăng ký danh tính",
    identityKey: "Mã định danh",
    accessProtocol: "Giao thức truy cập",
    terminateSession: "Kết thúc phiên",
    registryOverview: "Tổng quan đăng ký",
    quickProtocol: "Giao thức nhanh",
    activeModules: "Mô-đun hoạt động",
    structuralIntegrity: "Toàn vẹn cấu trúc: 100% Tối ưu",
    injectNewTest: "Thêm bài thi mới",
    viewSetupGuide: "Xem hướng dẫn thiết lập",
    noLogsDetected: "Không phát hiện nhật ký",
    exploreLibrary: "Khám phá thư viện",
    historicalInteraction: "Lịch sử tương tác của bạn với Hệ thống DNTRNG",
    // Landing Page
    library: "Thư viện",
    setupGuide: "Hướng dẫn",
    heroBadge: "Công cụ đánh giá chuyên nghiệp",
    heroTitleMain: "Kiểm tra",
    heroTitleItalic: "Đổi mới.",
    heroDesc: "Nền tảng hiệu suất cao cho các bài đánh giá tương tác, học tập trực quan và theo dõi trí tuệ thời gian thực.",
    enterLibrary: "Vào Thư viện",
    tryDemo: "Thử Bản mẫu",
    builtForLearning: "Xây dựng để học tập",
    masterSkills: "Làm chủ kỹ năng với các tương tác sâu.",
    feature1Title: "Vùng tương tác",
    feature1Desc: "Tương tác với các thử thách dựa trên hình ảnh bằng bản đồ chính xác.",
    feature2Title: "Trình tự Logic",
    feature2Desc: "Kéo và thả các mô-đun để sắp xếp các trình tự phức tạp.",
    feature3Title: "Phản hồi tức thì",
    feature3Desc: "Nhận thông tin chi tiết về mức độ hiệu suất của bạn trong thời gian thực.",
    ctaTitle: "Bắt đầu",
    ctaItalic: "Đánh giá.",
    ctaDesc: "Không yêu cầu thiết lập cho học sinh. Chỉ cần duyệt qua thư viện và bắt đầu hành trình của bạn.",
    openLibrary: "Mở Thư viện",
    footerDesc: "Trao quyền cho học sinh và giáo viên bằng các quy trình đánh giá chính xác và trí tuệ thời gian thực.",
    platform: "Nền tảng",
    resources: "Tài nguyên",
    setupProtocol: "Quy trình thiết lập",
    identityGuide: "Hướng dẫn định danh",
    cloudSync: "Đồng bộ đám mây",
    systemOptimal: "Hệ thống: Tốt"
  },
  es: {
    // Theme
    lightMode: "Modo Claro",
    darkMode: "Modo Oscuro",
    system: "Sistema",
    // Admin & General
    dashboard: "Panel",
    testLibrary: "Biblioteca de pruebas",
    students: "Estudiantes",
    results: "Resultados",
    activity: "Registro de actividad",
    logout: "Cerrar sesión",
    adminConsole: "Panel de control",
    statusActive: "Estado: Activo",
    lastSync: "Última sincronización",
    accessKey: "Clave de acceso",
    weeklySchedule: "Horario semanal",
    totalTests: "Total de pruebas",
    totalStudents: "Total de estudiantes",
    testResults: "Resultados de pruebas",
    avgScore: "Puntuación media",
    activityTrend: "Tendencia de actividad",
    recentResults: "Resultados recientes",
    seeAllResults: "Ver todos",
    quickActions: "Acciones rápidas",
    createTest: "Crear prueba",
    manageTests: "Gestionar pruebas",
    gsCode: "Código GS",
    syncData: "Sincronizar datos",
    seedData: "Cargar datos iniciales",
    searchTests: "Buscar pruebas...",
    newTest: "Nueva prueba",
    id: "ID",
    title: "Título",
    category: "Categoría",
    actions: "Acciones",
    questions: "PREGUNTAS",
    edit: "Editar",
    delete: "Eliminar",
    studentList: "Lista de estudiantes",
    addStudent: "Agregar estudiante",
    studentInfo: "Información del estudiante",
    role: "Rol",
    testsDone: "Pruebas realizadas",
    fullResultHistory: "Historial de resultados",
    date: "Fecha",
    student: "Estudiante",
    email: "Email",
    score: "Puntuación",
    result: "Resultado",
    passRate: "Tasa de aprobación",
    excellent: "EXCELENTE",
    pass: "APROBADO",
    fail: "REPROBADO",
    saveChanges: "Guardar cambios",
    addMultiple: "Agregar varios",
    studentManagement: "Gestión de Estudiantes",
    questionList: "Lista de Preguntas",
    manageQuestions: "Gestionar las preguntas de esta prueba",
    recentSubmissions: "Últimas entregas de estudiantes",
    weeklyKeys: "Las claves cambian automáticamente a medianoche.",
    noTests: "No se encontraron pruebas",
    noStudents: "No hay estudiantes registrados",
    noResults: "Aún no hay resultados",
    waitingFirst: "Esperando la primera entrega del estudiante...",
    confirmDeleteTitle: "¿Estás seguro?",
    confirmDeleteDesc: "Esto eliminará permanentemente este elemento y todos sus datos asociados. Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    timestamp: "Fecha y hora",
    event: "Evento",
    systemActivity: "Registros de actividad",
    monitorAccess: "Monitorear eventos de inicio y cierre de sesión",
    ipAddress: "Dirección IP",
    device: "Dispositivo",
    sessionArchive: "Archivo de Sesiones",
    identityRegistry: "Registro de Identidad",
    identityKey: "Clave de Identidad",
    accessProtocol: "Protocolo de Acceso",
    terminateSession: "Terminar Sesión",
    registryOverview: "Resumen del Registro",
    quickProtocol: "Protocolo Rápido",
    activeModules: "Módulos Activos",
    structuralIntegrity: "Integridad estructural: 100% Óptima",
    injectNewTest: "Inyectar Nueva Prueba",
    viewSetupGuide: "Ver Guía de Configuración",
    noLogsDetected: "No se detectaron registros",
    exploreLibrary: "Explorar Biblioteca",
    historicalInteraction: "Su interacción histórica con el Registro DNTRNG",
    // Landing Page
    library: "Biblioteca",
    setupGuide: "Guía de configuración",
    heroBadge: "Motor de Evaluación Profesional",
    heroTitleMain: "Pruebas",
    heroTitleItalic: "Re-imaginadas.",
    heroDesc: "La plataforma de alto rendimiento para evaluaciones interactivas, aprendizaje visual y seguimiento de inteligencia en tiempo real.",
    enterLibrary: "Entrar a la Biblioteca",
    tryDemo: "Probar Demo",
    builtForLearning: "Construido para el Aprendizaje",
    masterSkills: "Domina habilidades con interacciones profundas.",
    feature1Title: "Puntos de Interés Visual",
    feature1Desc: "Interactúa con desafíos basados en imágenes mediante mapeo de precisión.",
    feature2Title: "Secuencia Lógica",
    feature2Desc: "Arrastra y suelta módulos para organizar secuencias complejas.",
    feature3Title: "Retroalimentación Instantánea",
    feature3Desc: "Obtén información en tiempo real sobre tus niveles de rendimiento.",
    ctaTitle: "Comienza tu",
    ctaItalic: "Evaluación.",
    ctaDesc: "No se requiere configuración para los estudiantes. Simplemente navega por la biblioteca y comienza tu viaje.",
    openLibrary: "Abrir Biblioteca",
    footerDesc: "Empoderando a estudiantes y educadores con protocolos de evaluación de precisión e inteligencia en tiempo real.",
    platform: "Plataforma",
    resources: "Recursos",
    setupProtocol: "Protocolo de configuración",
    identityGuide: "Guía de identidad",
    cloudSync: "Sincronización en la nube",
    systemOptimal: "Sistema: Óptimo"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('dntrng_admin_lang') as Language;
    if (saved && (saved === 'en' || saved === 'vi' || saved === 'es')) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('dntrng_admin_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
